### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by rgstephens** [justintime4tea/nova-theme-materialize#1]
Thanks for posting this package. I tried it out and ran into this error:

```
Telescope/.meteor/local/build/programs/server/packages/nova_theme-materialize.js:163
import './components.js';
^^^^^^ 
SyntaxError: Unexpected reserved word
```

**Comment by justintime4tea** [comment]
Thank's for reporting this. Can you tell me a little bit about your setup? Which version of Nova, Node and NPM are you running? Did you ever get this hashed out? I took on some contract work and have been unable to attend to any of my personal projects so apologies for the lapse in response and updates to the package.

**Comment by rgstephens** [comment]
You can close this issue. I'm not using nova-theme-materialize.
